
package com.soap.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebCurrencyProvider", targetNamespace = "http://webservice.soap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebCurrencyProvider {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.soap.webservice.CurrencyData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllRates", targetNamespace = "http://webservice.soap.com/", className = "com.soap.webservice.GetAllRates")
    @ResponseWrapper(localName = "getAllRatesResponse", targetNamespace = "http://webservice.soap.com/", className = "com.soap.webservice.GetAllRatesResponse")
    public CurrencyData getAllRates(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0);

}
