
package com.soap.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebCalculator", targetNamespace = "http://webservice.soap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebCalculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://webservice.soap.com/", className = "com.soap.webservice.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://webservice.soap.com/", className = "com.soap.webservice.AddResponse")
    public double add(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://webservice.soap.com/", className = "com.soap.webservice.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://webservice.soap.com/", className = "com.soap.webservice.DivideResponse")
    public double divide(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://webservice.soap.com/", className = "com.soap.webservice.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://webservice.soap.com/", className = "com.soap.webservice.MultiplyResponse")
    public double multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtract", targetNamespace = "http://webservice.soap.com/", className = "com.soap.webservice.Subtract")
    @ResponseWrapper(localName = "subtractResponse", targetNamespace = "http://webservice.soap.com/", className = "com.soap.webservice.SubtractResponse")
    public double subtract(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sqr", targetNamespace = "http://webservice.soap.com/", className = "com.soap.webservice.Sqr")
    @ResponseWrapper(localName = "sqrResponse", targetNamespace = "http://webservice.soap.com/", className = "com.soap.webservice.SqrResponse")
    public double sqr(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
